version: '3.8'
services:
  mysql:
    image: mysql
    platform: linux/amd64
    container_name: mysql
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
    - mysql:/var/lib/mysql
    - .:/docker-entrypoint-initdb.d
volumes:
  mysql:
