spring:
  profiles:
    include: common
  r2dbc:
    url: r2dbc:mysql://localhost:3306/test
    username: root
    password: root
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
management:
  endpoints:
    web:
      exposure:
        include: metrics
