spring:
  profiles:
    include: common
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  tomcat:
    threads:
      max: 200
    mbeanregistry:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: *
